version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
  node:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm start


