# Generated by Django 4.1.7 on 2023-03-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kanalservis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_column='№', unique=True)),
                ('order', models.IntegerField(db_column='заказ№', unique=True)),
                ('price_usd', models.IntegerField(db_column='стоимость$')),
                ('price_rub', models.IntegerField(db_column='стоимостьРуб')),
                ('ord_date', models.DateTimeField(db_column='срок_поставки')),
            ],
        ),
    ]
