# Generated by Django 4.1.7 on 2023-03-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanalservis',
            name='ord_date',
            field=models.DateField(db_column='срок_поставки'),
        ),
    ]
